version: "3"

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network
  strapiproject:
    container_name: strapiproject
    build:
      context: ../../teststrapi/strapiproject
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 1337:1337
    networks:
      - app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true
